version: '3'
services:
  pgadmin4:
    build:
      context: .
      dockerfile: ./pgadmin4.dockerfile
    image: viniciuscsreis/pgadmin4
    volumes: 
      - "./pgadmin:/var/lib/pgadmin"
    container_name: pgadmin4-bd1
    ports:
      - "3001:80"
    networks: 
      - bd1
    depends_on:
      - "postgres"
  
  postgres:
    build:
      context: .
      dockerfile: ./postgres.dockerfile
    image: viniciuscsreis/postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    container_name: postgres-bd1
    ports:
      - "5432:5432"
    networks: 
      - bd1 
networks: 
  bd1:
    driver: bridge

